### ISSUE TITLE
Nested variables with same key name gives 'unused variable' error in GQL queries

### ISSUE THREAD

**Issue by spcogg** [DeloitteDigitalAPAC/GraphQLClient.jl#20]
Hey Mal, Think i'm getting something that's in the guts of how the GQLClient processes duplicate nested variables that's giving me an error.

I have a situation where a query that works in graphiql, that has variables that under first level nesting, has duplicate key names

The query looks like:

```
 query getHexAggregatedLinkMetrics(
  $viewState: ViewStateInput!
  $metric: RouteMetric!
  $dataSource: DataSource
) {
  getHexAggregatedLinkMetrics(
    viewState: $viewState
    metric: $metric
    dataSource: $dataSource
    compressData: false
  ) {
    actual
    baseline
    delta
  }
}
```
the variables look like this: notice how the refViewState and fullViewState have the same sub-keys underneath (this is by design)
```
{
	"viewState": {
		"browserId": "dd141199-bbca-4d61-ab78-165ce0069526",
		"refViewState": {
			"MACRO": [
				"86be63577ffffff"
			],
			"MICRO": []
		},
		"fullViewState": {
			"MACRO": [
				"86be63577ffffff"
			],
			"MICRO": []
		}
	},
	"dataSource": "FUSION",
	"metric": "V_KPH"
}
```

Raw Query string below (from graphiql)

> POST /bff_graphql HTTP/2
> Host: api.xxx.com
> user-agent: insomnia/2022.5.0
> content-type: application/json
> authorization: Bearer xxxx
> x-security-check: xxxx
> accept: */*
> content-length: 651

`
| {"query":"query getHexAggregatedLinkMetrics(\n  $viewState: ViewStateInput!\n  $metric: RouteMetric!\n  $dataSource: DataSource\n) {\n  getHexAggregatedLinkMetrics(\n    viewState: $viewState\n    metric: $metric\n    dataSource: $dataSource\n    compressData: false\n  ) {\n    actual\n    baseline\n    delta\n  }\n}","variables":{"viewState":{"browserId":"dd141199-bbca-4d61-ab78-165ce0069526","refViewState":{"MACRO":["86be63577ffffff"],"MESO":["86be63577ffffff"],"MICRO":[]},"fullViewState":{"MACRO":["86be63577ffffff"],"MESO":["86be63577ffffff"],"MICRO":[]}},"dataSource":"FUSION","metric":"V_KPH"},"operationName":"getHexAggregatedLinkMetrics"}
`

**In GQL Interface**
However, when i try to run the same query in GQLInterface:

![image](https://user-images.githubusercontent.com/8016236/186324299-520d8d40-dff4-4207-bb9f-b291909ca0db.png)

I've triaged it down to the fact that using GQLInterface, i think it tries to rename the nested variables and append them with `_1` and `_2` 

This is my variable dict in julia, which is generating this error:
```
viewstate = Dict(
    "fullViewState" => Dict(
    "MACRO" => ["86be63577ffffff"],
    "MICRO" => []
),
    "refViewState" => Dict(
    "MACRO" => ["86be63577ffffff"],
    "MICRO" => []
), 
    "browserId" => "dd141199-bbca-4d61-ab78-165ce0069526",
)
```

However if I change this dict to the following (removing the duplicate sub-keys), the query will work (but doesn't give the result i want...)
```
viewstate = Dict(
    "fullViewState" => Dict(
    "MACRO" => ["86be63577ffffff"],
),
    "refViewState" => Dict(
    "MICRO" => []
), 
    "browserId" => "dd141199-bbca-4d61-ab78-165ce0069526",
)
```

Does this make sense?

**Comment by spcogg** [comment]
also FYI @captchanjack  @BenjaminYong
Happy to make an update if you can point us in the right direction to make an update (or am i using something incorrect here)

**Comment by mmiller-max** [comment]
Hmm yeah I don't like this part of the code at all, feels like it's going to keep causing these sorts of errors! I'll have a think and see if I can suggest a way forward 👍

**Comment by mmiller-max** [comment]
@spcogg please can you share the `query_args` dictionary that is passed to `GraphQLClient.query`? Cheers!

**Comment by mmiller-max** [comment]
I'm trying to recreate what you're seeing but struggling! I suspect it's something to do with how it's handling a NamedType as a variable rather than just basic types, but hard to recreate.

Please could you paste the full query that `GraphQLClient.jl` is querying with? Should be printed if you set the `verbose` kwarg to 2 in `query`.

**Comment by spcogg** [comment]
Ah, so i figured out that you're supposed to pass `verbose=2` instead of `verbose=true` to get this to print, lol

And yes, as i thought, the problem variable generates the extra `1` or `2` at the end (see below)

```
 res = EMInterface.query(
           "getHexHistoricWay";
               query_args=Dict(
                   "viewState" => viewstate,
                   "dataSource" => "FUSION_BACK_PROPAGATED",
                   "metric" => "N_TRAFFIC_VOL",
                   "compressData" => false,
                   "historicTimestamp" => _ts
                   ),
               output_fields = ["historic", "compressedData"],
               verbose=2
           )
GraphQL input string is: 
 query(
    $dataSource: DataSource
    $metric: WayMetric
    $historicTimestamp: Int!
    $browserId: String!
    $MESO: [
        Hexadecimal
    ]
    $MACRO: [
        Hexadecimal
    ]
    $MESO__1: [
        Hexadecimal
    ]
    $MACRO__2: [
        Hexadecimal
    ]
    $compressData: Boolean
){
    getHexHistoricWay(
        dataSource:$dataSource
        metric:$metric
        historicTimestamp:$historicTimestamp
        viewState:{
            browserId:$browserId
            fullViewState:{
                MESO:$MESO
                MACRO:$MACRO
            }
            refViewState:{
                MESO:$MESO1
                MACRO:$MACRO2
            }
        }
        compressData:$compressData
    ){
        historic
        compressedData
    }
}
GraphQL input variables are: 
 Dict{String, Any}("MACRO__2" => ["86be63577ffffff", "86be63547ffffff", "86be63567ffffff", "86be63cdfffffff"], "MESO" => ["86be63577ffffff", "86be63547ffffff", "86be63567ffffff", "86be63cdfffffff"], "dataSource" => "FUSION_BACK_PROPAGATED", "metric" => "N_TRAFFIC_VOL", "historicTimestamp" => 1661397600, "browserId" => "dd141199-bbca-4d61-ab78-165ce0069526", "MESO__1" => ["86be63577ffffff", "86be63547ffffff", "86be63567ffffff", "86be63cdfffffff"], "MACRO" => ["86be63577ffffff", "86be63547ffffff", "86be63567ffffff", "86be63cdfffffff"], "compressData" => false)
```
![image](https://user-images.githubusercontent.com/8016236/186568284-f0057a9e-c010-460e-818b-03cb07333e5e.png)

Looking closer at this, I think it's in  https://github.com/DeloitteDigitalAPAC/GraphQLClient.jl/blob/main/src/output_fields.jl

Let me see if i can debug this and make a pr/fix

**Comment by mmiller-max** [comment]
I think you are using version 0.7.3, rather than 0.7.5. With 0.7.3 I get:

```
(
    dataSource:$dataSource
    metric:$metric
    viewstate:{
        browserId:$browserId
        fullViewState:{
            MACRO:$MACRO
            MICRO:$MICRO
        }
        refViewState:{
            MACRO:$MACRO1
            MICRO:$MICRO2
        }
    }
    historicTimestamp:$historicTimestamp
    compressData:$compressData
)
```
And with 0.7.5
```
(
    dataSource:$dataSource
    metric:$metric
    viewstate:{
        browserId:$browserId
        fullViewState:{
            MACRO:$MACRO
            MICRO:$MICRO
        }
        refViewState:{
            MACRO:$MACRO__1
            MICRO:$MICRO__2
        }
    }
    historicTimestamp:$historicTimestamp
    compressData:$compressData
)
```

Note the variable name is now correct

**Comment by mmiller-max** [comment]
It is interesting to compare this to the graphiql query though, where `viewState` is the variable rather than its lowest level fields. Would be interesting to understand the implications of this

**Comment by spcogg** [comment]
ah yes you're right - updating to 0.7.5 does fix my immediate issue (so happy to close)

And yes now that I understand this, it does appear graphiql passes the entire dict as a variable, which i guess means it does less checks on the variable introspection on the client side?

**Comment by mmiller-max** [comment]
> And yes now that I understand this, it does appear graphiql passes the entire dict as a variable, which i guess means it does less checks on the variable introspection on the client side?

Yes I think you're right from a quick look, GraphiQL will do more checking of variables as it will check the type of the various subfields of `viewState` when they're inputted, whilst GraphQLClient will only check that the dictionary keys (and keys of any sub-dictionaries) are in the schema, if that makes sense.

Could you quickly check that for me? If you run the query above but set (for example) `dataSource` to be an integer in both GraphiQL and GraphQLClient and see what happens? My guess is the former will show an error in the GUI and the latter will report an error from the server.

**Comment by spcogg** [comment]
Hey Sorry this took a while, but here's the results if you're still interested:
EMInterface:
![image](https://user-images.githubusercontent.com/8016236/188343852-8a7c7369-11b0-458e-9f22-186dad6d59b9.png)
GraphiQL (New and prettier version, FYI)
![image](https://user-images.githubusercontent.com/8016236/188343873-f8bd0bbc-75b6-4fa0-b788-6af16a590fd3.png)

**Comment by mmiller-max** [comment]
> So I guess it's still the same in the end hah

Interesting! Thanks for checking that :)
