### ISSUE TITLE
Example using Basic Authentication

### ISSUE THREAD

**Issue by rtarquini** [DeloitteDigitalAPAC/GraphQLClient.jl#23]
Not really an issue, more of a question.
Are there any examples using basic authentication? I cannot get the client to connect to an existing GraphQL server using basic (password) authentication.

**Comment by mmiller-max** [comment]
Does the example shown [here](https://deloitteoptimalreality.github.io/GraphQLClient.jl/stable/client/#Connecting-to-a-Server) work? This is passing a header containing a bearer token.

E.g.
```
client = Client(
    "https://myurl.com/queries",
    "wss://myurl.com/subscriptions",
    headers = Dict("Authorization" => "Bearer XXX"),
)
```

**Comment by rtarquini** [comment]
The problem seems be I can only access the graphql server via the localhost interface. So must be an configuration issue with the server implementation.
